// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static Future<FirebaseOptions> get currentPlatform async {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPJJc8uDdkOsUpELeoayS_50nr3B6Rc5w',
    appId: '1:354280393904:web:dabddf235a0394495abf75',
    messagingSenderId: '354280393904',
    projectId: 'all-in-one-management-d6e1d',
    authDomain: 'all-in-one-management-d6e1d.firebaseapp.com',
    storageBucket: 'all-in-one-management-d6e1d.firebasestorage.app',
    measurementId: 'G-9NZ5MLGW0S',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_SThSA9gLwtwROKK-QpULMqvJ5o7a0w0',
    appId: '1:354280393904:android:d00d8bcb793407195abf75',
    messagingSenderId: '354280393904',
    projectId: 'all-in-one-management-d6e1d',
    storageBucket: 'all-in-one-management-d6e1d.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEg0_vqgi5RPU63beqlfMAlkfpoBOhNmY',
    appId: '1:354280393904:ios:855e813c0e7398515abf75',
    messagingSenderId: '354280393904',
    projectId: 'all-in-one-management-d6e1d',
    storageBucket: 'all-in-one-management-d6e1d.firebasestorage.app',
    iosBundleId: 'com.example.aiom',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPJJc8uDdkOsUpELeoayS_50nr3B6Rc5w',
    appId: '1:354280393904:web:228a36634b0d6ff95abf75',
    messagingSenderId: '354280393904',
    projectId: 'all-in-one-management-d6e1d',
    authDomain: 'all-in-one-management-d6e1d.firebaseapp.com',
    storageBucket: 'all-in-one-management-d6e1d.firebasestorage.app',
    measurementId: 'G-G6M70WR81S',
  );
}
